# Generated by Django 3.2.4 on 2021-06-15 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('UPCEAN', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_tag_backend.barcode')),
            ],
        ),
    ]
